### ISSUE TITLE
Test failures in profiles.UserCRUDLTest.test_self

### ISSUE THREAD

**Issue by emullaney** [rapidpro/tracpro#12]
The following lines in test_self() fail. Please advise. Thank you.

https://github.com/rapidpro/tracpro/blob/master/tracpro/profiles/tests.py#L243-252
https://github.com/rapidpro/tracpro/blob/master/tracpro/profiles/tests.py#L261-262

**Comment by rowanseymour** [comment]
Not seen that before. Can you debug and see which asserts are failing and why?

**Comment by emullaney** [comment]
Spent quite a bit of time debugging but didn't get very far. I outlined all failures above but here's a little more info.

User is anonymous on these lines, which leads to a 302 and no form found.
https://github.com/rapidpro/tracpro/blob/master/tracpro/profiles/tests.py#L243-252

Do tests succeed for you?

**Comment by rowanseymour** [comment]
Not seen this error before and the CI build is passing: https://travis-ci.org/rapidpro/tracpro

Can you try rebuilding your virtualenv from pip-freeze.txt in case you've got an incorrect dependency?

**Comment by rebecca-caktus** [comment]
We managed to resolve this issue. I think it had a lot to do with settings configurations.
