### ISSUE TITLE
Email and password problem

### ISSUE THREAD

**Issue by supportticanalyse** [rapidpro/tracpro#188]
Hi everybody! I just deployed Tracpro according to the documentation but my current worries is that the interface asks me an email address and a password. I do not know what to put. can someone help me?
Thank you!

**Comment by ewheeler** [comment]
please refer to the tracpro and django documentation:

https://tracpro.readthedocs.io/en/latest/users/getting-started.html#creating-an-organization-in-tracpro

https://docs.djangoproject.com/en/1.9/ref/django-admin/#createsuperuser
