### ISSUE TITLE
configure available languages by org

### ISSUE THREAD

**Issue by ewheeler** [rapidpro/tracpro#2]
Currently, the available languages are configured in `settings_common.py` for the entire installation. As a multi-tenant app, this means that the list of available languages will include all languages for organization A, organization B, etc. which will get unruly once there are many users from many countries.

Instead, languages should be configurable for each organization (or perhaps based on the languages enabled in the corresponding RapidPro organization).

**Comment by nicpottier** [comment]
Hrmm? I think you are confusing the UI language with the flow languages.

Even optimistically I don't see the RapidPro UI being translated into more than a dozen languages, so that hardly seems to be getting out of control for a single dropdown to have that many options on your account settings screen.

Flow (or "translation") languages are indeed unique per organization.

**Comment by ewheeler** [comment]
I'm referring to the UI languages on tracpro. Currently all 5 languages are listed in the footer -- there is no dropdown.

**Comment by nicpottier** [comment]
Ah sorry, was thinking this was rapidpro not tracpro! doh.

Need better names. :)

**Comment by ewheeler** [comment]
@nicpottier lol. I think I tricked you with my other recent issue as well!

**Comment by rowanseymour** [comment]
This makes sense and is probably something that belongs in https://github.com/rapidpro/dash which contains the `Org` model. Available languages would still have to be configured in the settings, but the display list in the page footer would be configurable on a per-org basis.

**Comment by ewheeler** [comment]
@rowanseymour cool. i agree that dash is a good place for this

**Comment by norkans7** [comment]
For now dash Org has a language field that determine the language to activate for the org in U-report, I think we still put all the available languages in the settings and add a way to active a subset of those for an org. We currently support to activate just one language we can support activation of more that one.
I agree as well this belongs to dash.

**Comment by rebecca-caktus** [comment]
Fixed in tracpro in v0.51.
