### ISSUE TITLE
Rename `issue`?

### ISSUE THREAD

**Issue by ewheeler** [rapidpro/tracpro#8]
I find `Issue` to be a very confusing name for the model. 

`PollRun` might be a better choice, as the model has a similar relationship to TracPro's `Poll` as RapidPro's `FlowRun` has to its `Flow`. Its certainly not an exact mapping, as the `PollRun` is not a Contact's participation in a `Poll` but rather one instance of a recurring Poll

Other words that might make sense:
`invitation` - contacts are regularly invited to participate in a recurring poll
`collection` - survey data is collected for a poll periodically
`interview` - poll participants are interviewed periodically

**Comment by nicpottier** [comment]
Just a +1 on ```Issue``` being a really wonky name.

**Comment by rowanseymour** [comment]
I came up with `Issue` in the code because there is no noun equivalent of "conducting a poll". The equivalent of a `FlowRun` in TracPro is a `Response` and an `Issue` is a collection of `FlowRun`s which are from the same flow start. I don't think it's worth changing the model name here but we can easily change the display text to be "Runs" instead of "Issues" if that's clearer for users.

**Comment by rowanseymour** [comment]
Noticed today that we actually call it "Dates" in most places in the UI, e.g.

![screen shot 2015-05-18 at 10 23 52](https://cloud.githubusercontent.com/assets/675558/7676909/3d44b92a-fd48-11e4-8270-358b19a23b3e.png)

This seems like the least confusing for users tho obviously doesn't work as a model name. If someone wants to refactor the codebase to use `PollRun` I'm fine with that but I still prefer "Dates" in the UI.

**Comment by ewheeler** [comment]
I don't hate `Dates` for the UI (don't love it either..), but strongly prefer `PollRun` for the code 

 `dates` would be a massively confusing word to use for this in the codebase

**Comment by emullaney** [comment]
This issue was closed previously. `Issue` has been renamed to `PollRun`.
